name: Build and run tests (CI)

on:
  push:
    # On which branch
    branches: ["master"]
    # On which files
    # paths: ["scripts/scripts.js", "styles/styles.scss"]
  schedule:
    # Every Tuesday at 1PM UTC
    - cron: "0 14 * * 2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: "Build and run unit-tests with Maven"
        run: ./mvnw -B -e --update-snapshots clean verify package
